version: '2'

services:
  isbpanel-frontend-backend:
    container_name: isbpanel-frontend-backend
    image: isbpanel-frontend-backend:0.0.8
    build: .
    volumes:
    - ./frontend:/app/frontend
    ports:
      - 3011:3011
    restart: always